import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from pathlib import Path
from huggingface_hub import hf_hub_download
import logging


import sys
import os
_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_ROOT / "src" / "topic_modeling"))

logging.basicConfig(
    format="%(asctime)s - %(name)s - [%(levelname)s] - %(message)s",
    level=logging.DEBUG,
)

# Suppress transformers and numba logs
logging.getLogger("transformers").setLevel(logging.ERROR)
logging.getLogger("numba").setLevel(logging.ERROR)

log = logging.getLogger("TopicDiscovery")

API_KEY = os.getenv("HF_API_KEY") or st.secrets.get("HF_API_KEY")
MODEL_REPO = os.getenv("HF_MODEL_REPO") or st.secrets.get("HF_MODEL_REPO", "fxGRDN/bertopic-dblp-593k")

if API_KEY is None:
    st.warning("Hugging Face API key not found. Set HF_API_KEY in environment or Streamlit secrets.")

from src.topic_modeling.config import MODEL_PATH
from src.topic_modeling.model import load as load_model
from src.topic_modeling.topic_stats import (
    get_overview,
    get_topic_distribution,
    get_all_topic_keywords,
    get_keywords_for_topic,
    get_topic_similarity_matrix,
    get_representative_docs,
)

st.set_page_config(page_title="Topic Discovery",
                   page_icon="🗂️",
                    layout="wide")

# ── Load model ────────────────────────────────────────────────────────────────

@st.cache_resource
def load():
    model_variants = [Path(f"{MODEL_PATH}_cpu"), MODEL_PATH, Path(f"{MODEL_PATH}_gpu")]
    if not any(p.exists() for p in model_variants):
        log.info(f"No local model artifacts found. Downloading from Hugging Face repo '{MODEL_REPO}'...")
        for fname in ["bertopic_model_cpu", "bertopic_model", "bertopic_model_gpu"]:
            try:
                hf_hub_download(
                    repo_id=MODEL_REPO,
                    filename=fname,
                    local_dir=str(MODEL_PATH.parent),
                    token=API_KEY,
                )
                log.info(f"Downloaded {fname}")
            except Exception as exc:
                log.debug(f"Skipped {fname}: {exc}")

    try:
        log.info("Loading BERTopic model...")
        topic_model, _ = load_model(MODEL_PATH)
        return topic_model
    except Exception as exc:
        st.error(
            "Could not load BERTopic model artifacts. "
            "Please ensure the repository contains a compatible model variant "
            "(preferably `bertopic_model_cpu` saved in the same BERTopic/numba environment)."
        )
        st.caption(f"Model repo: {MODEL_REPO}")
        st.exception(exc)
        return None

topic_model = load()
if topic_model is None:
    st.stop()

# ── Page header ───────────────────────────────────────────────────────────────

st.title("🗂️ Topic Discovery")
st.markdown("""
This page presents the results of **BERTopic** topic modeling trained on a sample
of 10% of the previously processed publications.
""")

# ── Pipeline description ──────────────────────────────────────────────────────

with st.expander("Pipeline description", expanded=False):
    st.markdown("""
    ### Model pipeline

    | Step | Component | Configuration |
    |---|---|---|
    | **Embeddings** | `all-MiniLM-L6-v2` | `batch_size=512`, `normalize=True` |
    | **Dimensionality reduction** | UMAP | `n_components=5`, `n_neighbors=15`, `min_dist=0.0`, `metric=cosine` |
    | **Clustering** | HDBSCAN | `min_cluster_size=300`, `min_samples=5`, `metric=euclidean` |
    | **Vectorizer** | CountVectorizer | `ngram_range=(1,2)`, `min_df=5`, `max_df=0.9` |
    | **Representation** | KeyBERTInspired | top 10 words per topic |
    | **Topic reduction** | BERTopic `nr_topics=50` | merge by cosine similarity |

    ### Outlier reduction
    After initial clustering, outlier documents are reassigned using two sequential strategies:
    1. **Embeddings strategy** (`threshold=0.2`) – assigns each outlier to the nearest topic centroid by cosine similarity.
    2. **c-TF-IDF strategy** (`threshold=0.1`) – for remaining outliers, uses term frequency to find the best matching topic.

    ### Inference on full dataset
    The model was trained on a **10% (~600k) stratified sample**. All ~6M documents were then assigned topics
 with the same two-pass outlier reduction applied per batch.

    ### Topic labels
    Labels are generated by joining the **top 5 keywords** per topic (e.g. `neural network / image / classification / deep / cnn`).
    """)

# ── Topic distribution ────────────────────────────────────────────────────────

st.subheader("Topic Distribution")

dist_df = get_topic_distribution(topic_model)

col_chart, col_table = st.columns([2, 1])

fig = px.bar(
    dist_df.head(30),
    x="count",
    y="label",
    orientation="h",
    text="pct",
    labels={"count": "Documents", "label": "Topic"},
    title="Top 30 topics by document count",
    color="count",
    color_continuous_scale="Blues",
)
fig.update_traces(texttemplate="%{text}%", textposition="outside")
fig.update_layout(
    height=700,
    yaxis={"autorange": "reversed"},
    coloraxis_showscale=False,
    margin=dict(l=0, r=40, t=40, b=0),
)
st.plotly_chart(fig, use_container_width=True)

st.markdown("**All topics**")
st.dataframe(
    dist_df[["label", "count", "pct"]].rename(columns={"label": "Topic", "count": "Docs", "pct": "%"}),
    use_container_width=True,
    height=700,
)

st.divider()

# ── Topic keywords explorer ───────────────────────────────────────────────────

st.subheader("Topic Keywords Explorer")

topic_options = {
    f"{row['label']} ({row['count']:,} docs)": row["topic_id"]
    for _, row in dist_df.iterrows()
}
selected_label = st.selectbox("Select a topic", list(topic_options.keys()))
selected_tid = topic_options[selected_label]

kw_df = get_keywords_for_topic(topic_model, selected_tid, n_words=15)

col_kw_bar, col_kw_table = st.columns([2, 1])

with col_kw_bar:
    fig_kw = px.bar(
        kw_df,
        x="score",
        y="word",
        orientation="h",
        title=f"Top keywords – {selected_label}",
        labels={"score": "c-TF-IDF score", "word": "Keyword"},
        color="score",
        color_continuous_scale="Blues",
    )
    fig_kw.update_layout(
        yaxis={"autorange": "reversed"},
        coloraxis_showscale=False,
        height=450,
        margin=dict(l=0, r=20, t=40, b=0),
    )
    st.plotly_chart(fig_kw, use_container_width=True)

with col_kw_table:
    st.markdown("**Scores**")
    st.dataframe(
        kw_df.rename(columns={"rank": "#", "word": "Keyword", "score": "Score"}),
        use_container_width=True,
        hide_index=True,
        height=450,
    )

st.divider()

# ── Representative documents ──────────────────────────────────────────────────

st.subheader("Representative Documents")
st.markdown("Sample paper titles most representative of each topic.")

rep_df = get_representative_docs(topic_model)

if not rep_df.empty:
    rep_options = {
        f"{row['label']} ({dist_df[dist_df['topic_id'] == row['topic_id']]['count'].values[0]:,} docs)": row["topic_id"]
        for _, row in dist_df.iterrows()
        if row["topic_id"] in rep_df["topic_id"].values
    }
    rep_selected_label = st.selectbox("Select topic", list(rep_options.keys()), key="rep_select")
    rep_selected_tid = rep_options[rep_selected_label]

    docs_for_topic = rep_df[rep_df["topic_id"] == rep_selected_tid]["doc"].tolist()
    for i, doc in enumerate(docs_for_topic, 1):
        st.markdown(f"**{i}.** {doc}")
else:
    st.info("Representative documents not available – model may have been loaded without training data.")

st.divider()

# ── Topic similarity heatmap ──────────────────────────────────────────────────

st.subheader("Topic Similarity Matrix")
st.markdown("Cosine similarity between topic embeddings.")

with st.spinner("Computing similarity matrix..."):
    try:
        sim_df = get_topic_similarity_matrix(topic_model)

        # Truncate labels for readability
        short_labels = [l[:30] for l in sim_df.columns]

        fig_sim = go.Figure(data=go.Heatmap(
            z=sim_df.values,
            x=short_labels,
            y=short_labels,
            colorscale="RdBu_r",
            zmin=0,
            zmax=1,
            colorbar=dict(title="Cosine similarity"),
        ))
        fig_sim.update_layout(
            title="Topic–Topic Cosine Similarity",
            height=700,
            margin=dict(l=0, r=0, t=40, b=0),
            xaxis={"tickangle": -45, "tickfont": {"size": 9}},
            yaxis={"tickfont": {"size": 9}},
        )
        st.plotly_chart(fig_sim, use_container_width=True)
    except Exception as e:
        st.warning(f"Similarity matrix not available: {e}")

st.divider()

# ── Topic size distribution ───────────────────────────────────────────────────

st.subheader("Topic Size Distribution")

fig_hist = px.histogram(
    dist_df,
    x="count",
    nbins=20,
    labels={"count": "Documents per topic", "y": "Number of topics"},
    title="Distribution of topic sizes",
    color_discrete_sequence=["#4C78A8"],
)
fig_hist.update_layout(
    bargap=0.05,
    height=350,
    margin=dict(l=0, r=0, t=40, b=0),
)
st.plotly_chart(fig_hist, use_container_width=True)